//! GPU golden テストの**参照 PNG 生成・検証**（#31）。
//!
//! 既存の protanopia golden（`ue/test/protanopia_golden_test.dart`）は、Flutter の
//! FragmentProgram で GPU 描画した出力を「sensus CLI が生成した参照 PNG」と突き合わせ
//! る方式だが、sensus CLI は本リポに同梱されておらず参照の再生成ができなかった。
//!
//! 本モジュールは、プロジェクトが宣言する正本そのもの（`sensus_core::apply()`、
//! `apply_vision_cpu_rgba8` が薄く包む CPU 経路）を使って参照 RGBA を計算し、PNG として
//! 書き出す。これにより CLI 無しでも「正本と同一の参照」を再現でき、色変換系フィルタ
//! （protanopia / deuteranopia / tritanopia / achromatopsia）の golden を増やせる。
//!
//! - [`gen_color_golden_refs`] (`#[ignore]`): 参照 PNG を `ue/test/golden/` に書き出す
//!   一回限りのジェネレータ。`cargo test -- --ignored gen_color_golden_refs` で実行する。
//! - [`protanopia_ref_matches_sensus_core`]: 既存の commit 済み `protanopia_ref.png` が
//!   `sensus_core::apply()` 出力とビット一致することを検証し、本ジェネレータの方法論
//!   （rust apply = 既存 CLI 参照）が妥当であることを CI で守る。
//!
//! PNG の入出力は dev-dependency の `image`(+png feature) でのみ行う。本体 cdylib には
//! png codec を載せない（実機ランタイムに不要）。

#[cfg(test)]
mod tests {
    use crate::{apply_vision_cpu_rgba8, vision_uniforms, VisionFilter};
    use std::path::{Path, PathBuf};

    /// `ue/test/golden/` の絶対パス。`CARGO_MANIFEST_DIR` は `ue/rust/`。
    fn golden_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("test")
            .join("golden")
    }

    /// PNG を RGBA8 の (w, h, bytes) にデコードする。
    fn decode_rgba(path: &Path) -> (u32, u32, Vec<u8>) {
        let dynimg =
            image::open(path).unwrap_or_else(|e| panic!("failed to open {}: {e}", path.display()));
        let rgba = dynimg.to_rgba8();
        let (w, h) = rgba.dimensions();
        (w, h, rgba.into_raw())
    }

    /// 入力 PNG に `filter` を strength=1.0 で適用した参照 RGBA を返す（正本経路）。
    fn reference_rgba(filter: VisionFilter, input: &Path) -> (u32, u32, Vec<u8>) {
        let (w, h, src) = decode_rgba(input);
        let out = apply_vision_cpu_rgba8(filter, src, w, h, 1.0)
            .expect("sensus_core::apply must succeed on a valid RGBA buffer");
        (w, h, out)
    }

    /// 既存 commit 済み参照（CLI 由来）が `sensus_core::apply()` とビット一致することを
    /// 確認する。一致しなければ「rust apply を参照源に使う」方法論が破綻しているサイン
    /// なので、新規 golden の生成を信用してはならない。
    #[test]
    fn protanopia_ref_matches_sensus_core() {
        let dir = golden_dir();
        let input = dir.join("protanopia_input.png");
        let existing_ref = dir.join("protanopia_ref.png");

        let (rw, rh, expected) = decode_rgba(&existing_ref);
        let (gw, gh, actual) = reference_rgba(VisionFilter::Protanopia, &input);

        assert_eq!((gw, gh), (rw, rh), "dimensions diverge from committed ref");
        assert_eq!(
            actual, expected,
            "sensus_core::apply(Protanopia) does not reproduce the committed CLI ref \
             — the rust-apply reference methodology is unsound, do not generate goldens"
        );
    }

    /// 色変換系フィルタの参照 PNG を `ue/test/golden/` に書き出す一回限りのジェネレータ。
    ///
    /// 既定では実行しない（`#[ignore]`）。再生成するときだけ:
    ///   cargo test -- --ignored gen_color_golden_refs
    ///
    /// 入力は protanopia と同じ `protanopia_input.png` を共有し、出力を
    /// `<filter>_ref.png` として書き出す。空間・時間依存フィルタは GPU/CPU の
    /// カーネル差でピクセル等価にならないため、色行列・luma 重みで閉じる4種に限定する。
    #[test]
    #[ignore = "one-shot golden reference generator; run with --ignored when regenerating"]
    fn gen_color_golden_refs() {
        let dir = golden_dir();
        let input = dir.join("protanopia_input.png");
        let (w, h, _) = decode_rgba(&input);

        // (出力ファイル名 stem, フィルタ)。protanopia は既存 commit を尊重し再生成しない。
        let targets: [(&str, VisionFilter); 3] = [
            ("deuteranopia", VisionFilter::Deuteranopia),
            ("tritanopia", VisionFilter::Tritanopia),
            ("achromatopsia", VisionFilter::Achromatopsia),
        ];

        // Dart golden が各 .frag に setFloat する uniform を、正本 `vision_uniforms()`
        // から取り出して JSON に焼く。Dart 側は色行列・luma 重みを再実装せず、この
        // 生成物を読むだけにする（正本 = sensus_core の一元化を保つ）。`vision_uniforms`
        // は色変換系では `[uStrength, uMatrix0..8]` / `[uStrength, uRGBWeights]` を返す
        // （uResolution は含まない＝Dart 側で末尾に w,h を足す）。strength=1.0, time=0。
        let mut uniforms_json = String::from("{\n");
        uniforms_json.push_str(&format!(
            "  \"_comment\": \"GENERATED by rust golden_gen::gen_color_golden_refs. \
             Canonical uniforms from sensus_core via vision_uniforms(strength=1.0). \
             Dart appends uResolution (w,h) after these.\",\n  \"width\": {w}, \"height\": {h},\n  \"filters\": {{\n"
        ));

        for (i, (stem, filter)) in targets.iter().enumerate() {
            // 参照 PNG（CPU 正本経路）。
            let (rw, rh, rgba) = reference_rgba(*filter, &input);
            let out_path = dir.join(format!("{stem}_ref.png"));
            image::save_buffer(&out_path, &rgba, rw, rh, image::ColorType::Rgba8)
                .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));

            // 正本 uniforms（GPU 経路用）。
            let u = vision_uniforms(*filter, 1.0, 0.0, w, h);
            let body = u
                .iter()
                .map(|v| format!("{v:?}"))
                .collect::<Vec<_>>()
                .join(", ");
            let sep = if i + 1 < targets.len() { "," } else { "" };
            uniforms_json.push_str(&format!("    \"{stem}\": [{body}]{sep}\n"));

            eprintln!(
                "wrote {} ({rw}x{rh}), {} uniforms",
                out_path.display(),
                u.len()
            );
        }

        uniforms_json.push_str("  }\n}\n");
        let json_path = dir.join("color_uniforms.json");
        std::fs::write(&json_path, uniforms_json)
            .unwrap_or_else(|e| panic!("failed to write {}: {e}", json_path.display()));
        eprintln!("wrote {}", json_path.display());
    }
}
