// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/sensus_bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  VisionFilter dco_decode_box_autoadd_vision_filter(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VisionFilter dco_decode_vision_filter(dynamic raw);

  @protected
  VisionGlaucomaMode dco_decode_vision_glaucoma_mode(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  VisionFilter sse_decode_box_autoadd_vision_filter(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VisionFilter sse_decode_vision_filter(SseDeserializer deserializer);

  @protected
  VisionGlaucomaMode sse_decode_vision_glaucoma_mode(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_vision_filter> cst_encode_box_autoadd_vision_filter(
      VisionFilter raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_vision_filter();
    cst_api_fill_to_wire_vision_filter(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_f_32_strict> cst_encode_list_prim_f_32_strict(
      Float32List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_f_32_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
      List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_vision_filter(
      VisionFilter apiObj, ffi.Pointer<wire_cst_vision_filter> wireObj) {
    cst_api_fill_to_wire_vision_filter(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_vision_filter(
      VisionFilter apiObj, wire_cst_vision_filter wireObj) {
    if (apiObj is VisionFilter_Protanopia) {
      wireObj.tag = 0;
      return;
    }
    if (apiObj is VisionFilter_Deuteranopia) {
      wireObj.tag = 1;
      return;
    }
    if (apiObj is VisionFilter_Tritanopia) {
      wireObj.tag = 2;
      return;
    }
    if (apiObj is VisionFilter_Achromatopsia) {
      wireObj.tag = 3;
      return;
    }
    if (apiObj is VisionFilter_Tetrachromacy) {
      wireObj.tag = 4;
      return;
    }
    if (apiObj is VisionFilter_Myopia) {
      wireObj.tag = 5;
      return;
    }
    if (apiObj is VisionFilter_Hyperopia) {
      wireObj.tag = 6;
      return;
    }
    if (apiObj is VisionFilter_Presbyopia) {
      wireObj.tag = 7;
      return;
    }
    if (apiObj is VisionFilter_Astigmatism) {
      var pre_axis_deg = cst_encode_f_32(apiObj.axisDeg);
      wireObj.tag = 8;
      wireObj.kind.Astigmatism.axis_deg = pre_axis_deg;
      return;
    }
    if (apiObj is VisionFilter_Glaucoma) {
      var pre_mode = cst_encode_vision_glaucoma_mode(apiObj.mode);
      wireObj.tag = 9;
      wireObj.kind.Glaucoma.mode = pre_mode;
      return;
    }
    if (apiObj is VisionFilter_MacularDegeneration) {
      wireObj.tag = 10;
      return;
    }
    if (apiObj is VisionFilter_Hemianopia) {
      var pre_side = cst_encode_f_32(apiObj.side);
      wireObj.tag = 11;
      wireObj.kind.Hemianopia.side = pre_side;
      return;
    }
    if (apiObj is VisionFilter_TunnelVision) {
      wireObj.tag = 12;
      return;
    }
    if (apiObj is VisionFilter_Cataract) {
      var pre_seed = cst_encode_u_64(apiObj.seed);
      wireObj.tag = 13;
      wireObj.kind.Cataract.seed = pre_seed;
      return;
    }
    if (apiObj is VisionFilter_Floaters) {
      var pre_seed = cst_encode_u_64(apiObj.seed);
      var pre_density = cst_encode_f_32(apiObj.density);
      var pre_size = cst_encode_f_32(apiObj.size);
      var pre_gaze_x = cst_encode_f_32(apiObj.gazeX);
      var pre_gaze_y = cst_encode_f_32(apiObj.gazeY);
      wireObj.tag = 14;
      wireObj.kind.Floaters.seed = pre_seed;
      wireObj.kind.Floaters.density = pre_density;
      wireObj.kind.Floaters.size = pre_size;
      wireObj.kind.Floaters.gaze_x = pre_gaze_x;
      wireObj.kind.Floaters.gaze_y = pre_gaze_y;
      return;
    }
    if (apiObj is VisionFilter_Photophobia) {
      wireObj.tag = 15;
      return;
    }
    if (apiObj is VisionFilter_NightBlindness) {
      wireObj.tag = 16;
      return;
    }
    if (apiObj is VisionFilter_Vertigo) {
      wireObj.tag = 17;
      return;
    }
    if (apiObj is VisionFilter_BppvRotation) {
      wireObj.tag = 18;
      return;
    }
    if (apiObj is VisionFilter_VestibularNeuritis) {
      wireObj.tag = 19;
      return;
    }
    if (apiObj is VisionFilter_Diplopia) {
      var pre_offset_x = cst_encode_f_32(apiObj.offsetX);
      var pre_offset_y = cst_encode_f_32(apiObj.offsetY);
      var pre_ghost_strength = cst_encode_f_32(apiObj.ghostStrength);
      wireObj.tag = 20;
      wireObj.kind.Diplopia.offset_x = pre_offset_x;
      wireObj.kind.Diplopia.offset_y = pre_offset_y;
      wireObj.kind.Diplopia.ghost_strength = pre_ghost_strength;
      return;
    }
    if (apiObj is VisionFilter_Nystagmus) {
      var pre_amplitude = cst_encode_f_32(apiObj.amplitude);
      var pre_direction_deg = cst_encode_f_32(apiObj.directionDeg);
      wireObj.tag = 21;
      wireObj.kind.Nystagmus.amplitude = pre_amplitude;
      wireObj.kind.Nystagmus.direction_deg = pre_direction_deg;
      return;
    }
    if (apiObj is VisionFilter_Starbursts) {
      var pre_num_rays = cst_encode_u_32(apiObj.numRays);
      var pre_ray_length_ratio = cst_encode_f_32(apiObj.rayLengthRatio);
      var pre_threshold = cst_encode_f_32(apiObj.threshold);
      var pre_dispersion = cst_encode_f_32(apiObj.dispersion);
      wireObj.tag = 22;
      wireObj.kind.Starbursts.num_rays = pre_num_rays;
      wireObj.kind.Starbursts.ray_length_ratio = pre_ray_length_ratio;
      wireObj.kind.Starbursts.threshold = pre_threshold;
      wireObj.kind.Starbursts.dispersion = pre_dispersion;
      return;
    }
    if (apiObj is VisionFilter_EyeStrain) {
      wireObj.tag = 23;
      return;
    }
    if (apiObj is VisionFilter_DryEye) {
      wireObj.tag = 24;
      return;
    }
    if (apiObj is VisionFilter_Metamorphopsia) {
      var pre_freq = cst_encode_f_32(apiObj.freq);
      var pre_seed = cst_encode_u_64(apiObj.seed);
      wireObj.tag = 25;
      wireObj.kind.Metamorphopsia.freq = pre_freq;
      wireObj.kind.Metamorphopsia.seed = pre_seed;
      return;
    }
    if (apiObj is VisionFilter_ContrastSensitivity) {
      wireObj.tag = 26;
      return;
    }
    if (apiObj is VisionFilter_DetailLoss) {
      var pre_cell_size = cst_encode_u_32(apiObj.cellSize);
      wireObj.tag = 27;
      wireObj.kind.DetailLoss.cell_size = pre_cell_size;
      return;
    }
    if (apiObj is VisionFilter_Teichopsia) {
      wireObj.tag = 28;
      return;
    }
    if (apiObj is VisionFilter_FlickeringStars) {
      var pre_seed = cst_encode_u_64(apiObj.seed);
      wireObj.tag = 29;
      wireObj.kind.FlickeringStars.seed = pre_seed;
      return;
    }
  }

  @protected
  double cst_encode_f_32(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  int cst_encode_vision_glaucoma_mode(VisionGlaucomaMode raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vision_filter(
      VisionFilter self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vision_filter(VisionFilter self, SseSerializer serializer);

  @protected
  void sse_encode_vision_glaucoma_mode(
      VisionGlaucomaMode self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
    'store_dart_post_cobject',
  );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  WireSyncRust2DartDco wire__crate__api__sensus_bridge__apply_vision_cpu_rgba8(
    ffi.Pointer<wire_cst_vision_filter> filter,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> rgba8,
    int width,
    int height,
    double strength,
  ) {
    return _wire__crate__api__sensus_bridge__apply_vision_cpu_rgba8(
      filter,
      rgba8,
      width,
      height,
      strength,
    );
  }

  late final _wire__crate__api__sensus_bridge__apply_vision_cpu_rgba8Ptr =
      _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                ffi.Pointer<wire_cst_vision_filter>,
                ffi.Pointer<wire_cst_list_prim_u_8_loose>,
                ffi.Uint32,
                ffi.Uint32,
                ffi.Float,
              )>>(
    'frbgen_universal_experience_wire__crate__api__sensus_bridge__apply_vision_cpu_rgba8',
  );
  late final _wire__crate__api__sensus_bridge__apply_vision_cpu_rgba8 =
      _wire__crate__api__sensus_bridge__apply_vision_cpu_rgba8Ptr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_vision_filter>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            int,
            int,
            double,
          )>();

  WireSyncRust2DartDco wire__crate__api__sensus_bridge__vision_shader_glsl(
    ffi.Pointer<wire_cst_vision_filter> filter,
  ) {
    return _wire__crate__api__sensus_bridge__vision_shader_glsl(filter);
  }

  late final _wire__crate__api__sensus_bridge__vision_shader_glslPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_vision_filter>)>>(
    'frbgen_universal_experience_wire__crate__api__sensus_bridge__vision_shader_glsl',
  );
  late final _wire__crate__api__sensus_bridge__vision_shader_glsl =
      _wire__crate__api__sensus_bridge__vision_shader_glslPtr.asFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_vision_filter>)>();

  WireSyncRust2DartDco wire__crate__api__sensus_bridge__vision_uniform_layout(
    ffi.Pointer<wire_cst_vision_filter> filter,
  ) {
    return _wire__crate__api__sensus_bridge__vision_uniform_layout(filter);
  }

  late final _wire__crate__api__sensus_bridge__vision_uniform_layoutPtr =
      _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                  ffi.Pointer<wire_cst_vision_filter>)>>(
    'frbgen_universal_experience_wire__crate__api__sensus_bridge__vision_uniform_layout',
  );
  late final _wire__crate__api__sensus_bridge__vision_uniform_layout =
      _wire__crate__api__sensus_bridge__vision_uniform_layoutPtr.asFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_vision_filter>)>();

  WireSyncRust2DartDco wire__crate__api__sensus_bridge__vision_uniforms(
    ffi.Pointer<wire_cst_vision_filter> filter,
    double strength,
    double time,
    int width,
    int height,
  ) {
    return _wire__crate__api__sensus_bridge__vision_uniforms(
      filter,
      strength,
      time,
      width,
      height,
    );
  }

  late final _wire__crate__api__sensus_bridge__vision_uniformsPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_vision_filter>,
            ffi.Float,
            ffi.Float,
            ffi.Uint32,
            ffi.Uint32,
          )>>(
    'frbgen_universal_experience_wire__crate__api__sensus_bridge__vision_uniforms',
  );
  late final _wire__crate__api__sensus_bridge__vision_uniforms =
      _wire__crate__api__sensus_bridge__vision_uniformsPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_vision_filter>,
            double,
            double,
            int,
            int,
          )>();

  ffi.Pointer<wire_cst_vision_filter> cst_new_box_autoadd_vision_filter() {
    return _cst_new_box_autoadd_vision_filter();
  }

  late final _cst_new_box_autoadd_vision_filterPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_cst_vision_filter> Function()>>(
      'frbgen_universal_experience_cst_new_box_autoadd_vision_filter');
  late final _cst_new_box_autoadd_vision_filter =
      _cst_new_box_autoadd_vision_filterPtr
          .asFunction<ffi.Pointer<wire_cst_vision_filter> Function()>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(
              ffi.Int32)>>('frbgen_universal_experience_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_f_32_strict> cst_new_list_prim_f_32_strict(
    int len,
  ) {
    return _cst_new_list_prim_f_32_strict(len);
  }

  late final _cst_new_list_prim_f_32_strictPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_prim_f_32_strict> Function(ffi.Int32)>>(
      'frbgen_universal_experience_cst_new_list_prim_f_32_strict');
  late final _cst_new_list_prim_f_32_strict = _cst_new_list_prim_f_32_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_f_32_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(ffi.Int32)>>(
      'frbgen_universal_experience_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)>>(
      'frbgen_universal_experience_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
    'dummy_method_to_enforce_bundling',
  );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
    DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
    DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType
    = ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_VisionFilter_Astigmatism extends ffi.Struct {
  @ffi.Float()
  external double axis_deg;
}

final class wire_cst_VisionFilter_Glaucoma extends ffi.Struct {
  @ffi.Int32()
  external int mode;
}

final class wire_cst_VisionFilter_Hemianopia extends ffi.Struct {
  @ffi.Float()
  external double side;
}

final class wire_cst_VisionFilter_Cataract extends ffi.Struct {
  @ffi.Uint64()
  external int seed;
}

final class wire_cst_VisionFilter_Floaters extends ffi.Struct {
  @ffi.Uint64()
  external int seed;

  @ffi.Float()
  external double density;

  @ffi.Float()
  external double size;

  @ffi.Float()
  external double gaze_x;

  @ffi.Float()
  external double gaze_y;
}

final class wire_cst_VisionFilter_Diplopia extends ffi.Struct {
  @ffi.Float()
  external double offset_x;

  @ffi.Float()
  external double offset_y;

  @ffi.Float()
  external double ghost_strength;
}

final class wire_cst_VisionFilter_Nystagmus extends ffi.Struct {
  @ffi.Float()
  external double amplitude;

  @ffi.Float()
  external double direction_deg;
}

final class wire_cst_VisionFilter_Starbursts extends ffi.Struct {
  @ffi.Uint32()
  external int num_rays;

  @ffi.Float()
  external double ray_length_ratio;

  @ffi.Float()
  external double threshold;

  @ffi.Float()
  external double dispersion;
}

final class wire_cst_VisionFilter_Metamorphopsia extends ffi.Struct {
  @ffi.Float()
  external double freq;

  @ffi.Uint64()
  external int seed;
}

final class wire_cst_VisionFilter_DetailLoss extends ffi.Struct {
  @ffi.Uint32()
  external int cell_size;
}

final class wire_cst_VisionFilter_FlickeringStars extends ffi.Struct {
  @ffi.Uint64()
  external int seed;
}

final class VisionFilterKind extends ffi.Union {
  external wire_cst_VisionFilter_Astigmatism Astigmatism;

  external wire_cst_VisionFilter_Glaucoma Glaucoma;

  external wire_cst_VisionFilter_Hemianopia Hemianopia;

  external wire_cst_VisionFilter_Cataract Cataract;

  external wire_cst_VisionFilter_Floaters Floaters;

  external wire_cst_VisionFilter_Diplopia Diplopia;

  external wire_cst_VisionFilter_Nystagmus Nystagmus;

  external wire_cst_VisionFilter_Starbursts Starbursts;

  external wire_cst_VisionFilter_Metamorphopsia Metamorphopsia;

  external wire_cst_VisionFilter_DetailLoss DetailLoss;

  external wire_cst_VisionFilter_FlickeringStars FlickeringStars;
}

final class wire_cst_vision_filter extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external VisionFilterKind kind;
}

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_f_32_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Float> ptr;

  @ffi.Int32()
  external int len;
}
