// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'sensus_bridge.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `color_matrix_flat`, `from_sensus`, `from_sensus`, `from_sensus`, `from_sensus`, `from_sensus`, `to_sensus`, `to_sensus`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 指定フィルタの GLSL ES 3.00 ソースを返す。
///
/// **用途**: ビルド時に Flutter アセット（または impeller 変換前の中間 `.frag`）
/// へ書き出す同期スクリプト用。実機ランタイムでこの文字列を直接 Flutter の
/// `FragmentProgram` に流し込むことはできない（理由は docs/sensus-integration.md）。
///
/// sensus_core の全 vision フィルタに `*_glsl()` getter が存在するため、本関数は
/// 全 [`VisionFilter`] で非空ソースを返す（shader 非対応フィルタは無い）。
String visionShaderGlsl({required VisionFilter filter}) =>
    RustLib.instance.api.crateApiSensusBridgeVisionShaderGlsl(filter: filter);

/// 指定フィルタの uniform を、FragmentProgram に `setFloat(i, ..)` する順序の
/// flat な `Vec<f32>` にして返す。
///
/// `sampler2D uTexture`（= 入力画像）および `uMask`（floaters のマスク）は
/// `setFloat` の対象外なので含めない。Flutter 側では float uniform を `setFloat(0..)`
/// で順に積み、サンプラは `setImageSampler(..)` で別途渡す。各インデックスの意味は
/// [`vision_uniform_layout`] が返すラベルと一致する（同じ順序、同じ長さ）。
///
/// # 引数
/// - `strength`: 0.0..=1.0（範囲外・NaN は sensus 側 `normalize_strength` で clamp / NaN→0）。
/// - `time`: 秒単位の時間。時間依存フィルタ（Vertigo / BppvRotation）の `uTime` に渡す。
///   それ以外のフィルタでは無視される（sensus の uniforms getter が time を取らないため）。
/// - `width` / `height`: 入力画像のピクセルサイズ。解像度依存フィルタの半径・texel size・
///   resolution・aspect の算出に使う。
///
/// # u32 シード / count / int の扱い
/// GLSL で `uint`/`int` の uniform（`uSeed`, `uCount`）も f32 に詰める。f32 は 2^24 を
/// 超える整数を正確に表せないため、seed が巨大だと精度が落ちる（モジュール doc 参照）。
Float32List visionUniforms(
        {required VisionFilter filter,
        required double strength,
        required double time,
        required int width,
        required int height}) =>
    RustLib.instance.api.crateApiSensusBridgeVisionUniforms(
        filter: filter,
        strength: strength,
        time: time,
        width: width,
        height: height);

/// 指定フィルタの uniform レイアウト（各 `setFloat` インデックスのラベル）を返す。
///
/// 返る `Vec<String>` の長さと順序は [`vision_uniforms`] の `Vec<f32>` と一致する。
/// Dart 側はこのラベル列で「インデックス i は何の値か」を機械的に確認できる
/// （`.frag` の uniform 宣言順と突き合わせる用途）。
List<String> visionUniformLayout({required VisionFilter filter}) =>
    RustLib.instance.api
        .crateApiSensusBridgeVisionUniformLayout(filter: filter);

/// sensus-core の CPU `apply` を薄く公開する。全 [`VisionFilter`] に対応する
/// （sensus の `apply` は網羅 match なので payload 付きフィルタも CPU で適用可能）。
///
/// GPU（FragmentProgram）経路が主だが、テストや GPU 非対応環境のフォールバックに使う。
/// 生 RGBA8（`width * height * 4` バイト）を入力し、同じレイアウトの RGBA8 を返す。
///
/// 注意: これは sensus の `image::DynamicImage` 経路を通すため GPU 経路より遅い。
/// 大きな画像をリアルタイム処理する用途には使わないこと。
Uint8List applyVisionCpuRgba8(
        {required VisionFilter filter,
        required List<int> rgba8,
        required int width,
        required int height,
        required double strength}) =>
    RustLib.instance.api.crateApiSensusBridgeApplyVisionCpuRgba8(
        filter: filter,
        rgba8: rgba8,
        width: width,
        height: height,
        strength: strength);

/// sensus-core が正準化した複合体験のプリセット 4 種を Dart へ返す。
///
/// 順序固定: meniere / bppv / vestibular_neuritis / labyrinthitis。各体験の視覚・聴覚
/// フィルタと緊急度は sensus の `Experience::MENIERE` 等の const をミラーへ変換したもの。
/// 文言は含まない（`id`・分類のみ）。体験名・緊急度メッセージ・聴覚症状の説明は
/// Dart 側 i18n（#18）が解決する。
List<Experience> experiences() =>
    RustLib.instance.api.crateApiSensusBridgeExperiences();

/// 視覚 + 聴覚にまたがる「複合体験」の Dart 公開ミラー。`sensus_core::Experience` 由来。
///
/// sensus は pure・別バッファ（画像 / 音声）のため、メニエール病のような「回転性めまい
/// （視覚）＋ 難聴・耳鳴り（聴覚）」の複合症状を 1 バッファで表せない。`Experience` は
/// 「どの視覚フィルタとどの聴覚フィルタを組にすれば仕様どおりの複合体験になるか」の
/// 正準化を sensus から受け取る。Dart 側は三徴候の組み合わせをハードコードせず、
/// [`experiences`] から取得する。
///
/// `id` は安定した英語識別子（i18n キー）。文言（体験名・説明）は持たず、Dart 側 i18n が
/// `id` をキーに解決する。
class Experience {
  /// 安定した識別子（i18n キー等に使う英語 ID）。sensus は `&'static str` だが
  /// FRB は `String` で出す。
  final String id;

  /// 視覚側フィルタ（視覚要素が無い体験では `None`）。
  final VisionFilter? vision;

  /// 聴覚側フィルタ（聴覚要素が無い体験では `None`）。
  final HearingFilter? hearing;

  /// 受診喚起の緊急度。
  final Urgency urgency;

  const Experience({
    required this.id,
    this.vision,
    this.hearing,
    required this.urgency,
  });

  @override
  int get hashCode =>
      id.hashCode ^ vision.hashCode ^ hearing.hashCode ^ urgency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Experience &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          vision == other.vision &&
          hearing == other.hearing &&
          urgency == other.urgency;
}

@freezed
sealed class HearingFilter with _$HearingFilter {
  const HearingFilter._();

  /// 難聴: 高音域カット。
  const factory HearingFilter.hearingLoss() = HearingFilter_HearingLoss;

  /// 突発性難聴: 特定周波数帯の急激な損失。
  const factory HearingFilter.suddenHearingLoss({
    required double freqHz,
  }) = HearingFilter_SuddenHearingLoss;

  /// 騒音性難聴: 4 kHz 付近の損失。
  const factory HearingFilter.noiseInducedHearingLoss() =
      HearingFilter_NoiseInducedHearingLoss;

  /// 耳鳴り: 指定周波数の正弦波を常時ミックス。
  const factory HearingFilter.tinnitus({
    required double freqHz,
  }) = HearingFilter_Tinnitus;

  /// 音響過敏: 音量を異常に増幅。
  const factory HearingFilter.hyperacusis() = HearingFilter_Hyperacusis;

  /// ミソフォニア: `freq_hz` 中心のトリガー帯域を過剰増幅 + 歪み。
  const factory HearingFilter.misophonia({
    required double freqHz,
  }) = HearingFilter_Misophonia;

  /// 変音: 音を歪んだ・金属的な質感に加工。
  const factory HearingFilter.paracusis() = HearingFilter_Paracusis;

  /// 音楽音痴: 音程の違いを識別しにくくする。
  const factory HearingFilter.amusia() = HearingFilter_Amusia;

  /// ジスメロディア: 音楽を不快・歪んだ音に変換。
  const factory HearingFilter.dysmelodia() = HearingFilter_Dysmelodia;

  /// 音程シフト: 半音単位で全体音程をシフト。
  const factory HearingFilter.pitchShift({
    required double semitones,
  }) = HearingFilter_PitchShift;

  /// ダイプラクシス: 左右耳で異なる音程を知覚。
  const factory HearingFilter.diplacusis() = HearingFilter_Diplacusis;

  /// APD（聴覚情報処理障害）: 時間分解能低下 + 雑音付加。
  const factory HearingFilter.auditoryProcessingDisorder() =
      HearingFilter_AuditoryProcessingDisorder;

  /// メニエール病の聴覚側: 低音域難聴 + 低い唸る耳鳴り。
  const factory HearingFilter.meniere() = HearingFilter_Meniere;

  /// 迷路炎の聴覚側: 高音域感音難聴 + 高音の耳鳴り。
  const factory HearingFilter.labyrinthitis() = HearingFilter_Labyrinthitis;
}

/// 受診喚起の緊急度分類。`sensus_core::Urgency` の FRB 公開ミラー。
///
/// 文言は持たない（分類のみ）。⚠️/🚨 等の表示文言は Dart 側 i18n が
/// このバリアントをキーに出し分ける。
enum Urgency {
  /// 緊急性の注記なし。
  none,

  /// 早期受診が望ましい。
  earlyConsultation,

  /// 即救急（脳卒中等のサインの可能性）。
  emergency,
  ;
}

@freezed
sealed class VisionFilter with _$VisionFilter {
  const VisionFilter._();

  /// 1型2色覚（赤）。uniform: uStrength + uMatrix[9]。
  const factory VisionFilter.protanopia() = VisionFilter_Protanopia;

  /// 2型2色覚（緑）。uniform: uStrength + uMatrix[9]。
  const factory VisionFilter.deuteranopia() = VisionFilter_Deuteranopia;

  /// 3型2色覚（青黄）。uniform: uStrength + uMatrix[9]。
  const factory VisionFilter.tritanopia() = VisionFilter_Tritanopia;

  /// 全色盲。uniform: uStrength + RGB luma weights。
  const factory VisionFilter.achromatopsia() = VisionFilter_Achromatopsia;

  /// 四色型色覚。uniform: uStrength。
  const factory VisionFilter.tetrachromacy() = VisionFilter_Tetrachromacy;

  /// 近視（解像度依存の disk blur）。
  const factory VisionFilter.myopia() = VisionFilter_Myopia;

  /// 遠視（disk blur）。
  const factory VisionFilter.hyperopia() = VisionFilter_Hyperopia;

  /// 老視（disk blur）。
  const factory VisionFilter.presbyopia() = VisionFilter_Presbyopia;

  /// 乱視。`axis_deg`: シャープ方向の経線角（度数法、医学慣習）。
  const factory VisionFilter.astigmatism({
    required double axisDeg,
  }) = VisionFilter_Astigmatism;

  /// 緑内障。`mode`: 暗点モード。
  const factory VisionFilter.glaucoma({
    required VisionGlaucomaMode mode,
  }) = VisionFilter_Glaucoma;

  /// 加齢黄斑変性。
  const factory VisionFilter.macularDegeneration() =
      VisionFilter_MacularDegeneration;

  /// 半盲。`side`: 0.0 = 左視野消失, 1.0 = 右視野消失。
  const factory VisionFilter.hemianopia({
    required double side,
  }) = VisionFilter_Hemianopia;

  /// 視野狭窄（トンネル視）。
  const factory VisionFilter.tunnelVision() = VisionFilter_TunnelVision;

  /// 白内障。`seed`: 散乱グレア生成シード。
  const factory VisionFilter.cataract({
    required BigInt seed,
  }) = VisionFilter_Cataract;

  /// 飛蚊症。`seed`/`density`/`size`/`gaze_x`/`gaze_y`。
  const factory VisionFilter.floaters({
    required BigInt seed,
    required double density,
    required double size,
    required double gazeX,
    required double gazeY,
  }) = VisionFilter_Floaters;

  /// 羞明（解像度依存の bloom）。
  const factory VisionFilter.photophobia() = VisionFilter_Photophobia;

  /// 夜盲。
  const factory VisionFilter.nightBlindness() = VisionFilter_NightBlindness;

  /// 浮動性めまい（時間依存）。
  const factory VisionFilter.vertigo() = VisionFilter_Vertigo;

  /// BPPV 回転性めまい（時間依存）。
  const factory VisionFilter.bppvRotation() = VisionFilter_BppvRotation;

  /// 前庭神経炎。
  const factory VisionFilter.vestibularNeuritis() =
      VisionFilter_VestibularNeuritis;

  /// 複視。`offset_x`/`offset_y`: 幽霊像のずれ（min(W,H) 比のピクセル）, `ghost_strength`: 幽霊像強度。
  const factory VisionFilter.diplopia({
    required double offsetX,
    required double offsetY,
    required double ghostStrength,
  }) = VisionFilter_Diplopia;

  /// 眼振。`amplitude`: 振幅（min(W,H) 比）, `direction_deg`: 揺れ方向（度数法）。
  const factory VisionFilter.nystagmus({
    required double amplitude,
    required double directionDeg,
  }) = VisionFilter_Nystagmus;

  /// 光芒。`num_rays`/`ray_length_ratio`/`threshold`/`dispersion`。
  const factory VisionFilter.starbursts({
    required int numRays,
    required double rayLengthRatio,
    required double threshold,
    required double dispersion,
  }) = VisionFilter_Starbursts;

  /// 眼精疲労。
  const factory VisionFilter.eyeStrain() = VisionFilter_EyeStrain;

  /// ドライアイ。
  const factory VisionFilter.dryEye() = VisionFilter_DryEye;

  /// 変視症（歪み）。`freq`: 空間周波数, `seed`: 歪み場シード。
  const factory VisionFilter.metamorphopsia({
    required double freq,
    required BigInt seed,
  }) = VisionFilter_Metamorphopsia;

  /// コントラスト感度低下。
  const factory VisionFilter.contrastSensitivity() =
      VisionFilter_ContrastSensitivity;

  /// ディテールロス（ピクセル化）。`cell_size`: タイルサイズ (px)。
  const factory VisionFilter.detailLoss({
    required int cellSize,
  }) = VisionFilter_DetailLoss;

  /// 閃輝暗点。
  const factory VisionFilter.teichopsia() = VisionFilter_Teichopsia;

  /// 閃輝（光の星）。`seed`: ランダムシード。
  const factory VisionFilter.flickeringStars({
    required BigInt seed,
  }) = VisionFilter_FlickeringStars;
}

/// 緑内障の暗点モード。`sensus_core::vision::GlaucomaMode` の FRB 公開ミラー。
///
/// FRB は外部クレートの enum を直接 Dart へ出せないため、ue 側で同型を定義して
/// [`to_sensus`](VisionGlaucomaMode::to_sensus) で変換する。値は
/// `glaucoma.frag` の `uMode`（0..3）に 1 対 1 対応する。
enum VisionGlaucomaMode {
  /// 中心保存 + 周辺 smoothstep vignetting（既定）。uMode=0。
  vignette,

  /// 上方弧状暗点（Bjerrum 上方）。uMode=1。
  arcuateSuperior,

  /// 下方弧状暗点（Bjerrum 下方）。uMode=2。
  arcuateInferior,

  /// 両弧状暗点（進行例）。uMode=3。
  biarcuate,
  ;
}
