// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `color_matrix_flat`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// 指定フィルタの GLSL ES 3.00 ソースを返す。
///
/// **用途**: ビルド時に Flutter アセット（または impeller 変換前の中間 `.frag`）
/// へ書き出す同期スクリプト用。実機ランタイムでこの文字列を直接 Flutter の
/// `FragmentProgram` に流し込むことはできない（理由は docs/sensus-integration.md）。
String visionShaderGlsl({required VisionFilter filter}) =>
    RustLib.instance.api.crateApiSensusBridgeVisionShaderGlsl(filter: filter);

/// 指定フィルタの uniform を、FragmentProgram に `setFloat(i, ..)` する順序の
/// flat な `Vec<f32>` にして返す。
///
/// `sampler2D uTexture`（= 入力画像）は `setFloat` の対象外なので含めない。
/// Flutter 側では float uniform を `setFloat(0..)` で順に積み、サンプラは
/// `setImageSampler(0, ..)` で別途渡す。各インデックスの意味は
/// [`vision_uniform_layout`] が返すラベルと一致する（同じ順序）。
///
/// # 引数
/// - `strength`: 0.0..=1.0（範囲外は sensus 側で clamp される）。
/// - `width` / `height`: 入力画像のピクセルサイズ。解像度依存フィルタ
///   （Myopia / Photophobia）の半径・texel size 算出に使う。色覚 4 種では未使用。
/// - `seed`: ランダム系フィルタ用シード。MVP のフィルタでは未使用だが、後続で
///   Cataract / Floaters 等を足すときに使う（署名を安定させるため今から受ける）。
///
/// # 各フィルタの返却レイアウト
/// - Protanopia / Deuteranopia / Tritanopia:
///   `[uStrength, uMatrix0, uMatrix1, .., uMatrix8]`（計 10 要素）
/// - Achromatopsia: `[uStrength, uRWeight, uGWeight, uBWeight]`（計 4 要素）
/// - Myopia: `[uStrength, uRadiusPx, uTexelSizeX, uTexelSizeY]`（計 4 要素）
/// - Photophobia: `[uRadiusPx, uTexelSizeX, uTexelSizeY]`（計 3 要素。
///   photophobia.frag は `uStrength` を持たない — strength は半径へ畳み込み済み）
Float32List visionUniforms(
        {required VisionFilter filter,
        required double strength,
        required int width,
        required int height,
        required BigInt seed}) =>
    RustLib.instance.api.crateApiSensusBridgeVisionUniforms(
        filter: filter,
        strength: strength,
        width: width,
        height: height,
        seed: seed);

/// 指定フィルタの uniform レイアウト（各 `setFloat` インデックスのラベル）を返す。
///
/// 返る `Vec<String>` の長さと順序は [`vision_uniforms`] の `Vec<f32>` と一致する。
/// Dart 側はこのラベル列で「インデックス i は何の値か」を機械的に確認できる
/// （`.frag` の uniform 宣言順と突き合わせる用途）。
List<String> visionUniformLayout({required VisionFilter filter}) =>
    RustLib.instance.api
        .crateApiSensusBridgeVisionUniformLayout(filter: filter);

/// （将来用）sensus-core の CPU `apply` を 1 つだけ薄く公開する。
///
/// GPU（FragmentProgram）経路が主のため MVP では未使用だが、テストや
/// GPU 非対応環境のフォールバックに備えて残す。生 RGBA8（`width * height * 4`
/// バイト）を入力し、同じレイアウトの RGBA8 を返す。
///
/// 注意: これは sensus の `image::DynamicImage` 経路を通すため GPU 経路より遅い。
/// 大きな画像をリアルタイム処理する用途には使わないこと。
Uint8List applyVisionCpuRgba8(
        {required VisionFilter filter,
        required List<int> rgba8,
        required int width,
        required int height,
        required double strength}) =>
    RustLib.instance.api.crateApiSensusBridgeApplyVisionCpuRgba8(
        filter: filter,
        rgba8: rgba8,
        width: width,
        height: height,
        strength: strength);

/// Dart 側で扱う vision フィルタ（MVP サブセット）。
///
/// sensus_core::Filter のうち、本 Issue (#7, sensus 連携 1/3) でブリッジを
/// 通すものだけを列挙する。MVP は色覚 4 種 + 解像度依存の 2 例。全フィルタ網羅は
/// 後続フェーズで `sensus_core::Filter` 全バリアントへ拡張する。
///
/// パラメータは MVP では `strength` 中心とし、解像度依存フィルタは
/// [`vision_uniforms`] へ `width`/`height` を、ランダム系は `seed` を渡す。
enum VisionFilter {
  /// 1型2色覚（赤）。uniform: uStrength + uMatrix[9]。
  protanopia,

  /// 2型2色覚（緑）。uniform: uStrength + uMatrix[9]。
  deuteranopia,

  /// 3型2色覚（青黄）。uniform: uStrength + uMatrix[9]。
  tritanopia,

  /// 全色盲。uniform: uStrength + RGB luma weights。
  achromatopsia,

  /// 近視（解像度依存の disk blur）。uniform: uStrength + uRadiusPx + uTexelSize。
  myopia,

  /// 羞明（解像度依存の bloom）。uniform: uRadiusPx + uTexelSize（uStrength なし）。
  photophobia,
  ;
}
